/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BeletrieRouteImport } from './routes/beletrie'
import { Route as GenreRouteImport } from './routes/$genre'
import { Route as IndexRouteImport } from './routes/index'

const BeletrieRoute = BeletrieRouteImport.update({
  id: '/beletrie',
  path: '/beletrie',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreRoute = GenreRouteImport.update({
  id: '/$genre',
  path: '/$genre',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$genre': typeof GenreRoute
  '/beletrie': typeof BeletrieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$genre': typeof GenreRoute
  '/beletrie': typeof BeletrieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$genre': typeof GenreRoute
  '/beletrie': typeof BeletrieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$genre' | '/beletrie'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$genre' | '/beletrie'
  id: '__root__' | '/' | '/$genre' | '/beletrie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenreRoute: typeof GenreRoute
  BeletrieRoute: typeof BeletrieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/beletrie': {
      id: '/beletrie'
      path: '/beletrie'
      fullPath: '/beletrie'
      preLoaderRoute: typeof BeletrieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$genre': {
      id: '/$genre'
      path: '/$genre'
      fullPath: '/$genre'
      preLoaderRoute: typeof GenreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenreRoute: GenreRoute,
  BeletrieRoute: BeletrieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
